[project]
name = "laser-engraver-driver"
version = "0.1.0"
description = "A simple server for the DIY laser cutter"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyserial>=3.5",
]
